apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-usps-remu-pilot
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: usps-remu/environment/dev
    repoURL: https://github.ibm.com/usps-rapid-entry/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true