apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  labels:
    app: cnkt-event-listener
  name: cnkt-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - name: tp-sample-app-
      interceptors:
        - ref:
            name: "cel"
          params:
          - name: "filter"
            value: "header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/tp-client-engineering-tp' && body.repository.full_name == 'client-engineering-tp/tp-sample-app'"
      bindings:
        - ref: cnkt-trigger-binding
      template:
        ref: tp-sample-app-dev