---
# Source: tp-sample-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-sample-app
  annotations:
    app.openshift.io/vcs-ref: e5476fa35c3e6f756a4fe0076d9c8bdaafedcd55
    app.openshift.io/vcs-uri: https://github.com/client-engineering-tp/tp-sample-app
  labels:
    app.kubernetes.io/name: tp-sample-app
    helm.sh/chart: tp-sample-app-1.0.0-rc0.0.17
    app.kubernetes.io/instance: tp-sample-app
    app: tp-sample-app
    app.openshift.io/runtime: js
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: tp-sample-app
      app.kubernetes.io/instance: tp-sample-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tp-sample-app
        app.kubernetes.io/instance: tp-sample-app
    spec:
      containers:
        - name: tp-sample-app
          image: "quay.io/francinenguimdo/tp-sample-app:0.0.17"
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
#           livenessProbe:
#             httpGet:
#               path: /
#               port: http
#           readinessProbe:
#             httpGet:
#               path: /
#               port: http
          env:
            - name: INGRESS_HOST
              value: ""
            - name: PROTOCOLS
              value: ""
            - name: LOG_LEVEL
              value: "debug"
            # - name: CLIENT_CERT
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: CLIENT_CERT
            # - name: CLIENT_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: CLIENT_KEY
            # - name: CLIENT_CA
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: CLIENT_CA
            # - name: DB_HOST
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: DB_HOST
            # - name: DB_NAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: DB_NAME
            # - name: DB_PASS
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: DB_PASS
            # - name: DB_PORT
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: DB_PORT
            # - name: DB_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: DB_USER
            # - name: REACT_APP_API_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       key: REACT_APP_API_KEY
            #       name: tapestry-sample-api-key
            # - name: APP_ID_CLIENT_ID
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: APP_ID_CLIENT_ID
            # - name: APP_ID_TENANT_ID
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: APP_ID_TENANT_ID
            # - name: APP_ID_SECRET
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: APP_ID_SECRET
            # - name: APP_ID_NAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: APP_ID_NAME
            # - name: APP_ID_OAUTH_SERVER_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: APP_ID_OAUTH_SERVER_URL
            # - name: APP_ID_PROFILES_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: APP_ID_PROFILES_URL
            # - name: APP_ID_DISCOVERY_ENDPOINT
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: APP_ID_DISCOVERY_ENDPOINT
            # - name: APP_ID_REDIRECT_URI
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: APP_ID_REDIRECT_URI
            # - name: APP_ID_TYPE
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: APP_ID_TYPE
            # - name: SESSION_SECRET
            #   valueFrom:
            #     secretKeyRef:
            #       name: tapestry-sample
            #       key: SESSION_SECRET
          resources:
            null
